### ISSUE TITLE
Open surface model

### ISSUE THREAD

**Issue by camroo29** [rarora7777/curve-on-surface-drawing-vr#1]
Hi, 

I was trying to apply Stroke Mimicry on an open surface model. Seems like it only works with closed surface models. I would like to know if there is anyway it can be applied to open surface models as well.

Thanks

**Comment by rarora7777** [comment]
You should be able to use mimicry without Phong projection on an open surface. Unfortunately, I'm not aware of an easy way to extend Phong projection to open surfaces.
